<a href="https://colab.research.google.com/github/AVELURI12/Flight-Price-Prediction-Model/blob/main/Flight_Prediction_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/encoded_sampled_df.csv')
df.head()

,airline,source_city,destination_city,duration,days_until_departure,price,airline_code,flight_number,departure_time_Afternoon,departure_time_Early_Morning,...,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night,class_Business,class_Economy,PreExisting_Miles,Distance,Discount,Discounted_Price
0,Air_India,Delhi,Kolkata,19.75,40,7366.0,AI,506,0,0,...,0,0,0,0,0,1,54,816.0,13.50,7352.50
1,Vistara,Kolkata,Mumbai,9.83,42,64831.0,UK,706,0,0,...,0,0,0,1,1,0,45,1036.1,11.25,64819.75
2,Vistara,Kolkata,Bangalore,10.50,41,6195.0,UK,772,0,0,...,0,0,0,1,0,1,251,959.9,62.75,6132.25
3,Vistara,Chennai,Delhi,14.50,14,60160.0,UK,824,0,0,...,0,0,1,0,1,0,433,1089.7,108.25,60051.75
4,Air_India,Bangalore,Mumbai,8.25,20,6578.0,AI,501,1,0,...,0,0,0,1,0,1,379,517.1,94.75,6483.25

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Step 1: Feature-target split
X = df.drop(columns=['price'])
y = df['price']

# Step 2: One-hot encode all categorical variables (object dtype)
X = pd.get_dummies(X)

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 4: Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 5: Grid search for best k-NN parameters
param_grid = {
    'n_neighbors': [3, 5],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]  # Manhattan and Euclidean distances
}

grid = GridSearchCV(KNeighborsRegressor(), param_grid, cv=5,
                    scoring='neg_mean_squared_error', n_jobs=-1)
grid.fit(X_train_scaled, y_train)

# Step 6: Evaluate the best model
best_knn = grid.best_estimator_
y_pred = best_knn.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

# Step 7: Output
print(f"Best Parameters: {grid.best_params_}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.6f}")

Best Parameters: {'n_neighbors': 3, 'p': 1, 'weights': 'distance'}
MAE: 1641.94
RMSE: 3226.07
R² Score: 0.979791

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df1 = pd.read_csv('/content/drive/MyDrive/full_dataset_200k.csv')
df1.head()

<ipython-input-3-7600e768b745>:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('/content/drive/MyDrive/full_dataset_200k.csv')

,airline,source_city,destination_city,duration,days_until_departure,price,airline_code,flight_number,departure_time_Afternoon,departure_time_Early_Morning,...,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night,class_Business,class_Economy,PreExisitingMiles,Distance,Discount,Discounted_Price
0,Air_India,Delhi,Kolkata,19.75,40.0,7366.0,AI,506,0,0,...,0,0,0,0,0,1,285,816.0,142.5,7223.5
1,Vistara,Kolkata,Mumbai,9.83,42.0,64831.0,UK,706,0,0,...,0,0,0,1,1,0,985,1036.1,492.5,64338.5
2,Vistara,Kolkata,Bangalore,10.50,41.0,6195.0,UK,772,0,0,...,0,0,0,1,0,1,941,959.9,470.5,5724.5
3,Vistara,Chennai,Delhi,14.50,14.0,60160.0,UK,824,0,0,...,0,0,1,0,1,0,491,1089.7,245.5,59914.5
4,Air_India,Bangalore,Mumbai,8.25,20.0,6578.0,AI,501,1,0,...,0,0,0,1,0,1,168,517.1,84.0,6494.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Step 1: Load and prepare data
# Drop the target column
X = df1.drop(columns=['price'])

# Target variable
y = df1['price']

# One-hot encode categorical variables
X = pd.get_dummies(X)

# Step 2: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 3: Feature scaling (important for MLP)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 4: Train MLP Regressor
mlp = MLPRegressor(
    hidden_layer_sizes=(128, 64),  # two hidden layers
    activation='relu',
    solver='adam',
    max_iter=500,
    random_state=42,
    early_stopping=True
)

mlp.fit(X_train_scaled, y_train)

# Step 5: Predict and evaluate
y_pred = mlp.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

# Step 6: Display results
print("MLP Regressor Results:")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.6f}")

MLP Regressor Results:
MAE: 51.65
RMSE: 102.49
R² Score: 0.999980

In [ ]:
import pandas as pd
import numpy as np

# Create new data
new_data = pd.DataFrame([{
    'airline': 'Vistara',
    'source_city': 'Hyderabad',
    'destination_city': 'Bangalore',
    'duration': 21.67,
    'days_until_departure': 42,
    'price': 38099.0,
    'airline_code': 'UK',
    'flight_number': 876,
    'departure_time_Afternoon': 0,
    'departure_time_Early_Morning': 0,
    'departure_time_Evening': 0,
    'departure_time_Late_Night': 0,
    'departure_time_Morning': 0,
    'departure_time_Night': 1,
    'stops_one': 1,
    'stops_two_or_more': 0,
    'stops_zero': 0,
    'arrival_time_Afternoon': 0,
    'arrival_time_Early_Morning': 0,
    'arrival_time_Evening': 1,
    'arrival_time_Late_Night': 0,
    'arrival_time_Morning': 0,
    'arrival_time_Night': 0,
    'class_Business': 1,
    'class_Economy': 0,
    'PreExisitingMiles': 453,
    'Distance': 281.5,
    'Discount': 113.25,
    'Discounted_Price': 37985.75
}])

new_data = new_data.drop(columns=['price'])


# One-hot encode
new_data_encoded = pd.get_dummies(new_data)

# Match columns to training data
new_data_encoded = new_data_encoded.reindex(columns=X.columns, fill_value=0)

# Scale
new_data_scaled = scaler.transform(new_data_encoded)

# Predict
predicted_price = mlp.predict(new_data_scaled)
print(f"Predicted Price: {predicted_price[0]:.2f}")

Predicted Price: 33106.52